apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
        - name: website-container
          image: mudass3r/learning1:v1
          ports:
            - containerPort: 80
